# Generated by Django 4.2 on 2025-05-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_questionindicator_questionbank_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
