# Generated by Django 4.2 on 2025-05-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_profile_apa_pernah_pelatihan_profile_apa_sudah_ppg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
