# Generated by Django 4.2 on 2025-05-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bagian',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='kompetensi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
