# Generated by Django 4.2 on 2025-05-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_question_bagian_question_kompetensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='time_count',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
