# Generated by Django 4.2 on 2025-05-25 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0007_questionanswer_time_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='time_count',
            new_name='time_answer',
        ),
        migrations.CreateModel(
            name='QuestionTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_count', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
