# Generated by Django 4.2 on 2025-05-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_rename_time_count_questionanswer_time_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='time_answer',
            new_name='random',
        ),
    ]
