# Generated by Django 4.2 on 2025-05-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_rename_time_answer_questionanswer_random'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='random',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
