# Generated by Django 4.2 on 2025-05-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_alter_questionindicator_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionindicator',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
